//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interfaz_De_ususario.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PacienteDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_PacienteField;
        
        private int EdadField;
        
        private int TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Interfaz_De_ususario.ServiceReference1.Paciente PacienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdPaciente {
            get {
                return this.IdPacienteField;
            }
            set {
                if ((this.IdPacienteField.Equals(value) != true)) {
                    this.IdPacienteField = value;
                    this.RaisePropertyChanged("IdPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre_Paciente {
            get {
                return this.Nombre_PacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_PacienteField, value) != true)) {
                    this.Nombre_PacienteField = value;
                    this.RaisePropertyChanged("Nombre_Paciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((this.TelefonoField.Equals(value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Interfaz_De_ususario.ServiceReference1.Paciente Paciente {
            get {
                return this.PacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteField, value) != true)) {
                    this.PacienteField = value;
                    this.RaisePropertyChanged("Paciente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paciente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Paciente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SucesoDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SucesoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idSucesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sucesoField;
        
        private System.DateTime Fecha_SucesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Interfaz_De_ususario.ServiceReference1.Suceso Suceso1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idSuceso {
            get {
                return this.idSucesoField;
            }
            set {
                if ((this.idSucesoField.Equals(value) != true)) {
                    this.idSucesoField = value;
                    this.RaisePropertyChanged("idSuceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string suceso {
            get {
                return this.sucesoField;
            }
            set {
                if ((object.ReferenceEquals(this.sucesoField, value) != true)) {
                    this.sucesoField = value;
                    this.RaisePropertyChanged("suceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Fecha_Suceso {
            get {
                return this.Fecha_SucesoField;
            }
            set {
                if ((this.Fecha_SucesoField.Equals(value) != true)) {
                    this.Fecha_SucesoField = value;
                    this.RaisePropertyChanged("Fecha_Suceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Suceso", EmitDefaultValue=false, Order=3)]
        public Interfaz_De_ususario.ServiceReference1.Suceso Suceso1 {
            get {
                return this.Suceso1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Suceso1Field, value) != true)) {
                    this.Suceso1Field = value;
                    this.RaisePropertyChanged("Suceso1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Suceso", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Suceso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.PacientesSoap")]
    public interface PacientesSoap {
        
        // CODEGEN: Generating message contract since element name PacienteDto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarUsuario", ReplyAction="*")]
        Interfaz_De_ususario.ServiceReference1.InsertarUsuarioResponse InsertarUsuario(Interfaz_De_ususario.ServiceReference1.InsertarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Interfaz_De_ususario.ServiceReference1.InsertarUsuarioResponse> InsertarUsuarioAsync(Interfaz_De_ususario.ServiceReference1.InsertarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name Nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuarios", ReplyAction="*")]
        Interfaz_De_ususario.ServiceReference1.ListarUsuariosResponse ListarUsuarios(Interfaz_De_ususario.ServiceReference1.ListarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<Interfaz_De_ususario.ServiceReference1.ListarUsuariosResponse> ListarUsuariosAsync(Interfaz_De_ususario.ServiceReference1.ListarUsuariosRequest request);
        
        // CODEGEN: Generating message contract since element name ListaSucesosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaSucesos", ReplyAction="*")]
        Interfaz_De_ususario.ServiceReference1.ListaSucesosResponse ListaSucesos(Interfaz_De_ususario.ServiceReference1.ListaSucesosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaSucesos", ReplyAction="*")]
        System.Threading.Tasks.Task<Interfaz_De_ususario.ServiceReference1.ListaSucesosResponse> ListaSucesosAsync(Interfaz_De_ususario.ServiceReference1.ListaSucesosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public Interfaz_De_ususario.ServiceReference1.InsertarUsuarioRequestBody Body;
        
        public InsertarUsuarioRequest() {
        }
        
        public InsertarUsuarioRequest(Interfaz_De_ususario.ServiceReference1.InsertarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Interfaz_De_ususario.ServiceReference1.PacienteDTO PacienteDto;
        
        public InsertarUsuarioRequestBody() {
        }
        
        public InsertarUsuarioRequestBody(Interfaz_De_ususario.ServiceReference1.PacienteDTO PacienteDto) {
            this.PacienteDto = PacienteDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Interfaz_De_ususario.ServiceReference1.InsertarUsuarioResponseBody Body;
        
        public InsertarUsuarioResponse() {
        }
        
        public InsertarUsuarioResponse(Interfaz_De_ususario.ServiceReference1.InsertarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertarUsuarioResponseBody {
        
        public InsertarUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public Interfaz_De_ususario.ServiceReference1.ListarUsuariosRequestBody Body;
        
        public ListarUsuariosRequest() {
        }
        
        public ListarUsuariosRequest(Interfaz_De_ususario.ServiceReference1.ListarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        public ListarUsuariosRequestBody() {
        }
        
        public ListarUsuariosRequestBody(string Nombre) {
            this.Nombre = Nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Interfaz_De_ususario.ServiceReference1.ListarUsuariosResponseBody Body;
        
        public ListarUsuariosResponse() {
        }
        
        public ListarUsuariosResponse(Interfaz_De_ususario.ServiceReference1.ListarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Interfaz_De_ususario.ServiceReference1.PacienteDTO[] ListarUsuariosResult;
        
        public ListarUsuariosResponseBody() {
        }
        
        public ListarUsuariosResponseBody(Interfaz_De_ususario.ServiceReference1.PacienteDTO[] ListarUsuariosResult) {
            this.ListarUsuariosResult = ListarUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaSucesosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaSucesos", Namespace="http://tempuri.org/", Order=0)]
        public Interfaz_De_ususario.ServiceReference1.ListaSucesosRequestBody Body;
        
        public ListaSucesosRequest() {
        }
        
        public ListaSucesosRequest(Interfaz_De_ususario.ServiceReference1.ListaSucesosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaSucesosRequestBody {
        
        public ListaSucesosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaSucesosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaSucesosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Interfaz_De_ususario.ServiceReference1.ListaSucesosResponseBody Body;
        
        public ListaSucesosResponse() {
        }
        
        public ListaSucesosResponse(Interfaz_De_ususario.ServiceReference1.ListaSucesosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaSucesosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Interfaz_De_ususario.ServiceReference1.SucesoDTO[] ListaSucesosResult;
        
        public ListaSucesosResponseBody() {
        }
        
        public ListaSucesosResponseBody(Interfaz_De_ususario.ServiceReference1.SucesoDTO[] ListaSucesosResult) {
            this.ListaSucesosResult = ListaSucesosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PacientesSoapChannel : Interfaz_De_ususario.ServiceReference1.PacientesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PacientesSoapClient : System.ServiceModel.ClientBase<Interfaz_De_ususario.ServiceReference1.PacientesSoap>, Interfaz_De_ususario.ServiceReference1.PacientesSoap {
        
        public PacientesSoapClient() {
        }
        
        public PacientesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PacientesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacientesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacientesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interfaz_De_ususario.ServiceReference1.InsertarUsuarioResponse Interfaz_De_ususario.ServiceReference1.PacientesSoap.InsertarUsuario(Interfaz_De_ususario.ServiceReference1.InsertarUsuarioRequest request) {
            return base.Channel.InsertarUsuario(request);
        }
        
        public void InsertarUsuario(Interfaz_De_ususario.ServiceReference1.PacienteDTO PacienteDto) {
            Interfaz_De_ususario.ServiceReference1.InsertarUsuarioRequest inValue = new Interfaz_De_ususario.ServiceReference1.InsertarUsuarioRequest();
            inValue.Body = new Interfaz_De_ususario.ServiceReference1.InsertarUsuarioRequestBody();
            inValue.Body.PacienteDto = PacienteDto;
            Interfaz_De_ususario.ServiceReference1.InsertarUsuarioResponse retVal = ((Interfaz_De_ususario.ServiceReference1.PacientesSoap)(this)).InsertarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Interfaz_De_ususario.ServiceReference1.InsertarUsuarioResponse> Interfaz_De_ususario.ServiceReference1.PacientesSoap.InsertarUsuarioAsync(Interfaz_De_ususario.ServiceReference1.InsertarUsuarioRequest request) {
            return base.Channel.InsertarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Interfaz_De_ususario.ServiceReference1.InsertarUsuarioResponse> InsertarUsuarioAsync(Interfaz_De_ususario.ServiceReference1.PacienteDTO PacienteDto) {
            Interfaz_De_ususario.ServiceReference1.InsertarUsuarioRequest inValue = new Interfaz_De_ususario.ServiceReference1.InsertarUsuarioRequest();
            inValue.Body = new Interfaz_De_ususario.ServiceReference1.InsertarUsuarioRequestBody();
            inValue.Body.PacienteDto = PacienteDto;
            return ((Interfaz_De_ususario.ServiceReference1.PacientesSoap)(this)).InsertarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interfaz_De_ususario.ServiceReference1.ListarUsuariosResponse Interfaz_De_ususario.ServiceReference1.PacientesSoap.ListarUsuarios(Interfaz_De_ususario.ServiceReference1.ListarUsuariosRequest request) {
            return base.Channel.ListarUsuarios(request);
        }
        
        public Interfaz_De_ususario.ServiceReference1.PacienteDTO[] ListarUsuarios(string Nombre) {
            Interfaz_De_ususario.ServiceReference1.ListarUsuariosRequest inValue = new Interfaz_De_ususario.ServiceReference1.ListarUsuariosRequest();
            inValue.Body = new Interfaz_De_ususario.ServiceReference1.ListarUsuariosRequestBody();
            inValue.Body.Nombre = Nombre;
            Interfaz_De_ususario.ServiceReference1.ListarUsuariosResponse retVal = ((Interfaz_De_ususario.ServiceReference1.PacientesSoap)(this)).ListarUsuarios(inValue);
            return retVal.Body.ListarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Interfaz_De_ususario.ServiceReference1.ListarUsuariosResponse> Interfaz_De_ususario.ServiceReference1.PacientesSoap.ListarUsuariosAsync(Interfaz_De_ususario.ServiceReference1.ListarUsuariosRequest request) {
            return base.Channel.ListarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Interfaz_De_ususario.ServiceReference1.ListarUsuariosResponse> ListarUsuariosAsync(string Nombre) {
            Interfaz_De_ususario.ServiceReference1.ListarUsuariosRequest inValue = new Interfaz_De_ususario.ServiceReference1.ListarUsuariosRequest();
            inValue.Body = new Interfaz_De_ususario.ServiceReference1.ListarUsuariosRequestBody();
            inValue.Body.Nombre = Nombre;
            return ((Interfaz_De_ususario.ServiceReference1.PacientesSoap)(this)).ListarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interfaz_De_ususario.ServiceReference1.ListaSucesosResponse Interfaz_De_ususario.ServiceReference1.PacientesSoap.ListaSucesos(Interfaz_De_ususario.ServiceReference1.ListaSucesosRequest request) {
            return base.Channel.ListaSucesos(request);
        }
        
        public Interfaz_De_ususario.ServiceReference1.SucesoDTO[] ListaSucesos() {
            Interfaz_De_ususario.ServiceReference1.ListaSucesosRequest inValue = new Interfaz_De_ususario.ServiceReference1.ListaSucesosRequest();
            inValue.Body = new Interfaz_De_ususario.ServiceReference1.ListaSucesosRequestBody();
            Interfaz_De_ususario.ServiceReference1.ListaSucesosResponse retVal = ((Interfaz_De_ususario.ServiceReference1.PacientesSoap)(this)).ListaSucesos(inValue);
            return retVal.Body.ListaSucesosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Interfaz_De_ususario.ServiceReference1.ListaSucesosResponse> Interfaz_De_ususario.ServiceReference1.PacientesSoap.ListaSucesosAsync(Interfaz_De_ususario.ServiceReference1.ListaSucesosRequest request) {
            return base.Channel.ListaSucesosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Interfaz_De_ususario.ServiceReference1.ListaSucesosResponse> ListaSucesosAsync() {
            Interfaz_De_ususario.ServiceReference1.ListaSucesosRequest inValue = new Interfaz_De_ususario.ServiceReference1.ListaSucesosRequest();
            inValue.Body = new Interfaz_De_ususario.ServiceReference1.ListaSucesosRequestBody();
            return ((Interfaz_De_ususario.ServiceReference1.PacientesSoap)(this)).ListaSucesosAsync(inValue);
        }
    }
}
